import { Button } from './components/core/Button.jsx';
import { IconButton } from './components/core/IconButton.jsx';
import { Icon } from './components/core/Icon.jsx';
import { Field } from './components/forms/Field.jsx';
import { Input } from './components/forms/Input.jsx';
import { Textarea } from './components/forms/Textarea.jsx';
import { Select } from './components/forms/Select.jsx';
import { Checkbox } from './components/forms/Checkbox.jsx';
import { Radio } from './components/forms/Radio.jsx';
import { RadioGroup } from './components/forms/RadioGroup.jsx';
import { Switch } from './components/forms/Switch.jsx';
import { Card } from './components/content/Card.jsx';
import { Badge } from './components/content/Badge.jsx';
import { Tag } from './components/content/Tag.jsx';
import { List } from './components/content/List.jsx';
import { Table } from './components/content/Table.jsx';
import { Accordion } from './components/content/Accordion.jsx';
import { Alert } from './components/feedback/Alert.jsx';
import { Toast } from './components/feedback/Toast.jsx';
import { Tooltip } from './components/feedback/Tooltip.jsx';
import { Dialog } from './components/feedback/Dialog.jsx';
import { Link } from './components/navigation/Link.jsx';
import { Carousel } from './components/interaction/Carousel.jsx';
import { DisclosureMenu } from './components/interaction/DisclosureMenu.jsx';
import { Tabs } from './components/navigation/Tabs.jsx';
import { Breadcrumb } from './components/navigation/Breadcrumb.jsx';
const lib = { Button, IconButton, Icon, Field, Input, Textarea, Select, Checkbox, Radio, RadioGroup, Switch, Card, Badge, Tag, List, Table, Accordion, Alert, Toast, Tooltip, Dialog, Link, Tabs, Breadcrumb, DisclosureMenu, Carousel };
window.PUKWeb = lib;
